# TSL

## Cálculo das autofrequências

## Importação dos módulos necessários

In [6]:
import TSL
import numpy as np
import pandas as pd

## Leitura dos dados dos planetas

In [7]:
# Leitura dos dados
#input_file = sys.argv[1]
input_file = "planetas.txt"

# Lendo nome dos planetas
planetas = pd.read_table(input_file, skiprows = 8, delim_whitespace = True)

## Verificação dos dados

* m: massa [em unidades de massa solar]
* a: semieixo maior [au]
* e: excentricidade
* inc: inclinação [deg]

In [8]:
print(planetas)

   Planeta         m         a         e      inc
0  Jupiter  0.000955  5.202545  0.047462  1.30667
1  Saturno  0.000286  9.554841  0.057548  2.48795


## Atribuição dos valores

In [9]:
# Constante da gravitação universal
G = (0.01720209895)**2 # para o SS AU^3 d^-2 M_sol^-1

# Massa do Sol
M = 1.0 # Massa 'unitária' para o Sol

# Semieixo maior
a = planetas['a'] #[au]

# Massa
m = planetas['m'] # Considerando massa unitária para o Sol

# Dados dos movimentos médios n calculado
n = (G * (M + m)/a**3)**(1/2) #[rad/day]

# Excentricidade
e = planetas['e']

# Inclinação
inc = planetas['inc'] # [deg]

## Cálculo dos autovalores

In [10]:
# Cálculo dos autovalores e autovetores
A, B, Aval, Avec, Bval, Bvec = TSL.FreqProp (G, a, m, n)

print('Auto frequências [deg/yr]')
print(Aval)
print(Bval)

Auto frequências [deg/yr]
[ 0.00096381  0.00610026]
[ -8.67361738e-19  -7.06406493e-03]


In [11]:
# Cálculo dos autovalores e autovetores


print('Auto frequências g [arcsec/yr]')
print('f', '\t\t', 'g')
for (i, j) in zip(Aval, Bval):
    print(i * 3600,'\t', j * 3600)

Auto frequências g [arcsec/yr]
f 		 g
3.46971303973 	 -3.12250225676e-15
21.9609206972 	 -25.430633737


In [12]:
print(A)

[[ 0.00203832 -0.00133048]
 [-0.00328047  0.00502575]]


In [13]:
print(Aval)

[ 0.00096381  0.00610026]


In [16]:
print(Bval)

[ -8.67361738e-19  -7.06406493e-03]


In [14]:
print(Avec)

[[-0.77797183  0.31127449]
 [-0.62829915 -0.95032005]]


In [15]:
print(Bvec)

[[ 0.70710678 -0.37583998]
 [ 0.70710678  0.92668458]]


In [17]:
print(Aval * 3600)

[  3.46971304  21.9609207 ]


In [18]:
print(Bval * 3600)

[ -3.12250226e-15  -2.54306337e+01]
